### ISSUE TITLE
Compilation error: 'Array' does not contain a definition for 'Empty'.

### ISSUE THREAD

**Issue by ChloeLeitch** [Popax21/Styline#1]
Hi, I've been trying to compile the Styline mod to add my own features. However, it fails with this error.

![image](https://user-images.githubusercontent.com/40130389/210124812-8c0f55b6-c3ee-4caf-83e0-a6abf54230fe.png)

`/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Settings.cs(53,74): error CS0117: 'Array' does not contain a definition for 'Empty' [/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Styline.csproj]`

I would appreciate any assistance.

**Comment by Popax21** [comment]
Ah thanks, this seems to have slipped through the cracks - my build setup is sort of messed up, and seems to be able to somehow compile these things anyway (if you're on Linux as well, and are willing to share your dotnet setup so that this doesn't happen, then please let me know)

Also, I don't know what exactly you're trying to do, but Styline already is fairly customizable without having to create a new derived mod - simply create a skeleton mod with new Styline-related files in the `Contents` folder, it will automatically pick those up. If you're adding a new ability to Styline though, it would still be best to PR and merge that into the base mod, but if you're creating a completely custom mod skinmod though, then it is probably better to base it directly of Procedurline, and use Styline only as a reference to look up some details. Procedurline is pretty well documented, and features xmldocs + an extensive GitHub wiki for you to take a look at.

**Comment by ChloeLeitch** [comment]
I'm using dotnet 6 on Fedora.
I'm trying to make a skinmod with a few different skins and the ability to switch between them, so perhaps Procedurline would be better? I need to control hair length, clothing colors, accessories, etc.

**Comment by Popax21** [comment]
> I need to control hair length, clothing colors, accessories, etc.

Actually all of these are already configurable through custom Styline files, you don't need to create a new mod / modify the Styline code.

**Comment by ChloeLeitch** [comment]
To elaborate, the different skins would be a new menu option that lets you choose between preset combinations of hair color, length and other attributes. There are also some things that Styline does not let me do, like change skin color, and I'd like to add that functionality.

I am still unable to compile the code, running `dotnet --info` gives me this:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.112
 Commit:    d311a58ee1

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.112/

global.json file:
  Not found

Host:
  Version:      6.0.12
  Architecture: x64
  Commit:       02e45a41b7

.NET SDKs installed:
  6.0.112 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

If you run this as well it might give enough information to figure out the differences between our two environments.

**Comment by Popax21** [comment]
Stuff like presets / new filters would probably something which should be merged into the base mod - Styline isn't intended to be copy-pasted and modified for different skinmods, so it's probably best if you code up the new filters you have in mind, and PR them here.

Also, thanks for your setup dump! I'll take a look at it tomorrow. Could you in the meantime still provide your current compilation log, just in case?

**Comment by ChloeLeitch** [comment]
Sure thing!
```
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Settings.cs(53,74): error CS0117: 'Array' does not contain a definition for 'Empty' [/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Styline.csproj]

Build FAILED.

/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Settings.cs(53,74): error CS0117: 'Array' does not contain a definition for 'Empty' [/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Styline.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.97
```

**Comment by Popax21** [comment]
> Sure thing!
> 
> ```
> Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
> /mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Settings.cs(53,74): error CS0117: 'Array' does not contain a definition for 'Empty' [/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Styline.csproj]
> 
> Build FAILED.
> 
> /mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Settings.cs(53,74): error CS0117: 'Array' does not contain a definition for 'Empty' [/mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/BasilSkinMod/Code/Styline/Styline.csproj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:02.97
> ```

Huh, that's the same error - are you sure you pulled the latest changes?

**Comment by ChloeLeitch** [comment]
Oops. Working now!
Here's the output:
```
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Styline -> /mnt/harddisk/SteamLibrary/steamapps/common/Celeste/Mods/Styline/Code/Styline/bin/Debug/net452/Styline.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.10
```
Thanks for fixing that :D
